---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-mysql
type: Opaque
data:
stringData:
  conjur-map: |-
    username: data/vault/bnl-ocp-safe/mysql-test-db/username
    password: data/vault/bnl-ocp-safe/mysql-test-db/password
