---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secrets-provider-for-k8s-sidecar
type: Opaque
data:
stringData:
  conjur-map: |-
    username: $APP_SECRET_USERNAME_PATH
    password: $APP_SECRET_PASSWORD_PATH
    address: $APP_SECRET_ADDRESS_PATH