apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_PUSH_FILE_SIDECAR
  name: $APP_PUSH_FILE_SIDECAR
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $APP_PUSH_FILE_SIDECAR
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_PUSH_FILE_SIDECAR
      annotations:
        # Secrets Provider configuration
        conjur.org/container-mode: sidecar
        conjur.org/secrets-destination: file
        conjur.org/jwt-token-path: /var/run/secrets/tokens/jwt
        conjur.org/conjur-secrets-policy-path.test-app: $APP_SECRET_BASE_PATH
        conjur.org/conjur-secrets.test-app: |
          - username
          - password
          - address
        conjur.org/secret-file-format.test-app: "template"
        conjur.org/secret-file-path.test-app: "./application.yaml"
        conjur.org/secrets-refresh-interval: 60s
        conjur.org/secrets-refresh-enabled: "true"
    spec:
      serviceAccountName: $APP_PUSH_FILE_SIDECAR-sa
      containers:
        - name: $APP_PUSH_FILE_SIDECAR
          image: $APP_IMAGE_NAME_BASIC
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /opt/secrets/conjur/
          # Path to the file with the secrets
          volumeMounts:
            - name: conjur-secrets
              mountPath: /opt/secrets/conjur
              readOnly: true
            - name: conjur-templates
              mountPath: /conjur/templates
          ports:
            - containerPort: 8181
        - image: $SECRETS_PROVIDER_IMAGE
          imagePullPolicy: IfNotPresent
          name: configurator
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - name: podinfo
              mountPath: /conjur/podinfo
            - name: conjur-secrets
              mountPath: /conjur/secrets
            - name: conjur-templates
              mountPath: /conjur/templates
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
      volumes:
        - name: conjur-templates
          configMap:
            name: spring-boot-templates
        - name: conjur-secrets
          emptyDir:
            medium: Memory
        - name: conjur-status
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
        - emptyDir:
            medium: Memory
          name: conjur-access-token
        - emptyDir:
            medium: Memory
          name: conjur-certs
        - downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
          name: podinfo
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_PUSH_FILE_SIDECAR
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8181
      nodePort: 32092
  selector:
    app: $APP_PUSH_FILE_SIDECAR