---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-mysql
type: Opaque
data:
stringData:
  conjur-map: |-
    username: data/vault/bnl-k8s-safe/mysql-test-db/username
    password: data/vault/bnl-k8s-safe/mysql-test-db/password
    database: data/vault/bnl-k8s-safe/mysql-test-db/Database
