---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secrets-provider-for-k8s-sidecar
type: Opaque
data:
stringData:
  conjur-map: |-
    spring.datasource.username: data/vault/bnl-k8s-safe/mysql-test-db/username
    spring.datasource.password: data/vault/bnl-k8s-safe/mysql-test-db/password
    spring.datasource.url: data/vault/bnl-k8s-safe/mysql-test-db/DSN
    test.client-id: data/bnl-ocp-apps/secrets/demo-app-secrets-provider-sidecar-sa/client-id
    test.client-secret: data/bnl-ocp-apps/secrets/demo-app-secrets-provider-sidecar-sa/client-secret